export const projectsTab = [
  {
    id: 0,
    class: 'spotify',
    name: 'Spotify app',
    desc: 'Simple app integrated with Spotify API. Created in React & Redux.',
    codeLink: 'https://github.com/Lasecki99/Spotify-app',
    liveLink: 'https://lasecki99.github.io/Spotify-app/',
  },
  {
    id: 1,
    class: 'movie',
    name: 'The Movie Finder',
    desc:
      'Find your favorite movie and find out more about it! Created in React.',
    codeLink: 'https://github.com/Lasecki99/The-Movie-Finder',
    liveLink: 'https://lasecki99.github.io/The-Movie-Finder/',
  },
  {
    id: 2,
    class: 'burger',
    name: 'Burger app',
    desc:
      'Add ingredients, build and order your own Burger ! Created in React and Firebase.',
    codeLink: 'https://github.com/Lasecki99/Burger-app',
    liveLink: 'https://lasecki99.github.io/Burger-app/',
  },
  {
    id: 3,
    class: 'map',
    name: 'Interactive world map',
    desc: 'Responsive world map with centering on the smartphone.',
    codeLink: 'https://github.com/Lasecki99/the-world-map',
    liveLink: 'https://lasecki99.github.io/the-world-map/',
  },
  {
    id: 4,
    class: 'weather',
    name: 'React Weather App',
    desc: "It's a simple application showing the weather in your city.",
    codeLink: 'https://github.com/Lasecki99/React-Weather-App',
    liveLink: 'https://lasecki99.github.io/React-Weather-App/',
  },
  {
    id: 5,
    class: 'chuck',
    name: 'Chuck Norris App',
    desc: 'Generate a funny joke about Chuck Norris. Created with Typescript.',
    codeLink: 'https://github.com/Lasecki99/Chuck-Norris-App/',
    liveLink: 'https://lasecki99.github.io/Chuck-Norris-App/',
  },
  {
    id: 6,
    class: 'portfolio',
    name: 'Portfolio',
    desc: 'View code of my portfolio.',
    codeLink: 'https://github.com/Lasecki99/Portfolio',
  },
  {
    id: 7,
    class: 'rock',
    name: 'Rock paper scissors',
    desc: "It's a classic game using JavaScript.",
    codeLink: 'https://github.com/Lasecki99/Rock-Paper-Scissors',
    liveLink: 'https://lasecki99.github.io/Rock-Paper-Scissors/',
  },
  {
    id: 8,
    class: 'website',
    name: 'My first homepage',
    desc: 'It is my first website',
    codeLink: 'https://github.com/Lasecki99/Strona-wizytowka',
    liveLink: 'https://lasecki99.github.io/Strona-wizytowka/',
  },
  {
    id: 9,
    class: 'banner',
    name: 'Banner',
    desc: 'a simple banner made in javascript.',
    codeLink: 'https://github.com/Lasecki99/Slider-Banner',
    liveLink: 'https://lasecki99.github.io/Slider-Banner/',
  },
  {
    id: 10,
    class: 'slider',
    name: 'Scroll Animation',
    desc: 'Scroll Animation made in JQuery.',
    codeLink: 'https://github.com/Lasecki99/Scroll-Animation',
    liveLink: 'https://lasecki99.github.io/Scroll-Animation/',
  },
  {
    id: 11,
    name: 'Spotify App',
    desc: 'Simple app integrated with Spotify API. Created in React & Redux.',
    codeLink: 'https://github.com/Lasecki99/Spotify-app',
    liveLink: 'https://lasecki99.github.io/Spotify-app/',
  },
];
